spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka