server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**
        - id: CART-SERVICE
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/carts/**
        - id: ORDER-SERVICE
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: NOTI-SERVICE
          uri: lb://noti-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/v1/**, /api/v1/auth/**, /api/v1/users/**, /api/v1/address/**, /connect/v1/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
